title: ML Project - Fraud Detection in Transactions
description: Saarang Prabhuram, Rohan Batra, Shane Sinnerine, Richard Zhao, Maniya Dahiya
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman